import {
  User,
  SemesterResult,
  SubjectAttendance,
  DailyAttendanceRecord,
  FeeInvoice,
  DocumentItem,
  NotificationItem,
  StudentRecord,
  CourseAssignment,
  TimetableSlot,
} from './types';

export const CURRENT_STUDENT: User = {
  id: 'usr_std_101',
  name: 'Aarav Sharma',
  email: 'aarav.sharma@sap-campus.edu',
  role: 'student',
  studentId: 'SAP-CS-2023-049',
  department: 'Computer Science & Engineering',
  program: 'B.Tech - Computer Science',
  currentSemester: 5,
  enrollmentYear: 2023,
  phone: '+91 98765 43210',
  address: 'Block B-4, Tech Campus Enclave, Bengaluru, KA 560100',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const CURRENT_TEACHER: User = {
  id: 'usr_fac_202',
  name: 'Dr. Meera Nambiar',
  email: 'meera.nambiar@sap-campus.edu',
  role: 'teacher',
  teacherId: 'SAP-FAC-CS-018',
  department: 'Computer Science & Engineering',
  program: 'Senior Professor & HOD Advisory',
  phone: '+91 98111 22334',
  address: 'Staff Quarters Q-12, University Campus',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
};

export const CURRENT_ADMIN: User = {
  id: 'usr_adm_001',
  name: 'Rajesh Varma (Registrar)',
  email: 'admin.erp@sap-campus.edu',
  role: 'admin',
  adminId: 'SAP-ADM-SYS-001',
  department: 'Academic Administration & Registrar Office',
  phone: '+91 99000 88776',
  address: 'Central Administrative Building, Level 3',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
};

export const SEMESTER_RESULTS: SemesterResult[] = [
  {
    semesterNumber: 5,
    academicYear: '2025-2026',
    examMonthYear: 'December 2025',
    issueDate: 'January 14, 2026',
    marksheetNo: 'SAP-MS-2025-05-88421',
    sgpa: 8.85,
    cgpa: 8.72,
    totalCredits: 22,
    resultStatus: 'Passed with Distinction',
    subjects: [
      {
        code: 'CS-501',
        title: 'Cloud Architecture & Microservices',
        credits: 4,
        internalMarks: 28,
        maxInternal: 30,
        externalMarks: 64,
        maxExternal: 70,
        totalMarks: 92,
        maxTotal: 100,
        grade: 'A+',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Dr. Meera Nambiar',
      },
      {
        code: 'CS-502',
        title: 'Database Internals & Distributed Systems',
        credits: 4,
        internalMarks: 26,
        maxInternal: 30,
        externalMarks: 60,
        maxExternal: 70,
        totalMarks: 86,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Prof. Ramesh Kulkarni',
      },
      {
        code: 'CS-503',
        title: 'Software Engineering & SAP ABAP/UI5',
        credits: 4,
        internalMarks: 29,
        maxInternal: 30,
        externalMarks: 65,
        maxExternal: 70,
        totalMarks: 94,
        maxTotal: 100,
        grade: 'O (Outstanding)',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Dr. Anita Desai',
      },
      {
        code: 'CS-504',
        title: 'Artificial Intelligence & Machine Learning',
        credits: 4,
        internalMarks: 25,
        maxInternal: 30,
        externalMarks: 57,
        maxExternal: 70,
        totalMarks: 82,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Prof. Vikram Sen',
      },
      {
        code: 'CS-505P',
        title: 'Cloud & AI Lab Practical',
        credits: 3,
        internalMarks: 46,
        maxInternal: 50,
        externalMarks: 47,
        maxExternal: 50,
        totalMarks: 93,
        maxTotal: 100,
        grade: 'A+',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Dr. Meera Nambiar',
      },
      {
        code: 'CS-506P',
        title: 'Industrial Mini Project & Seminar',
        credits: 3,
        internalMarks: 44,
        maxInternal: 50,
        externalMarks: 45,
        maxExternal: 50,
        totalMarks: 89,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Dr. Anita Desai',
      },
    ],
  },
  {
    semesterNumber: 4,
    academicYear: '2024-2025',
    examMonthYear: 'June 2025',
    issueDate: 'July 10, 2025',
    marksheetNo: 'SAP-MS-2025-04-74319',
    sgpa: 8.65,
    cgpa: 8.68,
    totalCredits: 22,
    resultStatus: 'Passed with Distinction',
    subjects: [
      {
        code: 'CS-401',
        title: 'Operating Systems & Concurrency',
        credits: 4,
        internalMarks: 25,
        maxInternal: 30,
        externalMarks: 59,
        maxExternal: 70,
        totalMarks: 84,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Dr. Rajesh Rao',
      },
      {
        code: 'CS-402',
        title: 'Computer Networks & Security',
        credits: 4,
        internalMarks: 27,
        maxInternal: 30,
        externalMarks: 61,
        maxExternal: 70,
        totalMarks: 88,
        maxTotal: 100,
        grade: 'A+',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Prof. Sandeep Joshi',
      },
      {
        code: 'CS-403',
        title: 'Design & Analysis of Algorithms',
        credits: 4,
        internalMarks: 26,
        maxInternal: 30,
        externalMarks: 58,
        maxExternal: 70,
        totalMarks: 84,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Dr. Meera Nambiar',
      },
      {
        code: 'CS-404',
        title: 'Formal Languages & Automata Theory',
        credits: 4,
        internalMarks: 24,
        maxInternal: 30,
        externalMarks: 55,
        maxExternal: 70,
        totalMarks: 79,
        maxTotal: 100,
        grade: 'B+',
        gradePoints: 8,
        status: 'Pass',
        facultyName: 'Prof. Ramesh Kulkarni',
      },
      {
        code: 'CS-405P',
        title: 'Algorithms & Networks Lab',
        credits: 3,
        internalMarks: 45,
        maxInternal: 50,
        externalMarks: 46,
        maxExternal: 50,
        totalMarks: 91,
        maxTotal: 100,
        grade: 'A+',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Dr. Rajesh Rao',
      },
      {
        code: 'HS-401',
        title: 'Professional Ethics & Economics',
        credits: 3,
        internalMarks: 43,
        maxInternal: 50,
        externalMarks: 44,
        maxExternal: 50,
        totalMarks: 87,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Dr. Sunita Kapoor',
      },
    ],
  },
  {
    semesterNumber: 3,
    academicYear: '2024-2025',
    examMonthYear: 'December 2024',
    issueDate: 'January 18, 2025',
    marksheetNo: 'SAP-MS-2024-03-61102',
    sgpa: 8.70,
    cgpa: 8.70,
    totalCredits: 21,
    resultStatus: 'Passed with Distinction',
    subjects: [
      {
        code: 'CS-301',
        title: 'Data Structures with C++',
        credits: 4,
        internalMarks: 28,
        maxInternal: 30,
        externalMarks: 62,
        maxExternal: 70,
        totalMarks: 90,
        maxTotal: 100,
        grade: 'A+',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Dr. Meera Nambiar',
      },
      {
        code: 'CS-302',
        title: 'Digital Electronics & Microprocessors',
        credits: 4,
        internalMarks: 24,
        maxInternal: 30,
        externalMarks: 58,
        maxExternal: 70,
        totalMarks: 82,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Prof. T. K. Pillai',
      },
      {
        code: 'CS-303',
        title: 'Object Oriented Programming in Java',
        credits: 4,
        internalMarks: 27,
        maxInternal: 30,
        externalMarks: 63,
        maxExternal: 70,
        totalMarks: 90,
        maxTotal: 100,
        grade: 'A+',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Prof. Vikram Sen',
      },
      {
        code: 'MA-301',
        title: 'Discrete Mathematics & Probability',
        credits: 4,
        internalMarks: 25,
        maxInternal: 30,
        externalMarks: 56,
        maxExternal: 70,
        totalMarks: 81,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Dr. K. S. Raman',
      },
      {
        code: 'CS-304P',
        title: 'Data Structures & OOP Lab',
        credits: 3,
        internalMarks: 46,
        maxInternal: 50,
        externalMarks: 47,
        maxExternal: 50,
        totalMarks: 93,
        maxTotal: 100,
        grade: 'O (Outstanding)',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Dr. Meera Nambiar',
      },
      {
        code: 'HS-301',
        title: 'Environmental Science & Sustainability',
        credits: 2,
        internalMarks: 42,
        maxInternal: 50,
        externalMarks: 43,
        maxExternal: 50,
        totalMarks: 85,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Prof. Lata Hegde',
      },
    ],
  },
  {
    semesterNumber: 2,
    academicYear: '2023-2024',
    examMonthYear: 'June 2024',
    issueDate: 'July 15, 2024',
    marksheetNo: 'SAP-MS-2024-02-49801',
    sgpa: 8.60,
    cgpa: 8.70,
    totalCredits: 20,
    resultStatus: 'Passed with Distinction',
    subjects: [
      {
        code: 'CS-201',
        title: 'Programming Methodology in C',
        credits: 4,
        internalMarks: 26,
        maxInternal: 30,
        externalMarks: 60,
        maxExternal: 70,
        totalMarks: 86,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Prof. Ramesh Kulkarni',
      },
      {
        code: 'PH-201',
        title: 'Applied Physics & Quantum Mechanics',
        credits: 4,
        internalMarks: 25,
        maxInternal: 30,
        externalMarks: 58,
        maxExternal: 70,
        totalMarks: 83,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Dr. H. P. Roy',
      },
      {
        code: 'MA-201',
        title: 'Calculus, Linear Algebra & ODE',
        credits: 4,
        internalMarks: 27,
        maxInternal: 30,
        externalMarks: 62,
        maxExternal: 70,
        totalMarks: 89,
        maxTotal: 100,
        grade: 'A+',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Dr. K. S. Raman',
      },
      {
        code: 'EE-201',
        title: 'Basic Electrical & Electronic Engineering',
        credits: 4,
        internalMarks: 24,
        maxInternal: 30,
        externalMarks: 54,
        maxExternal: 70,
        totalMarks: 78,
        maxTotal: 100,
        grade: 'B+',
        gradePoints: 8,
        status: 'Pass',
        facultyName: 'Prof. M. B. Nair',
      },
      {
        code: 'CS-202P',
        title: 'Computing Workshop & C Lab',
        credits: 2,
        internalMarks: 45,
        maxInternal: 50,
        externalMarks: 47,
        maxExternal: 50,
        totalMarks: 92,
        maxTotal: 100,
        grade: 'A+',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Prof. Ramesh Kulkarni',
      },
      {
        code: 'PH-202P',
        title: 'Engineering Physics Lab',
        credits: 2,
        internalMarks: 43,
        maxInternal: 50,
        externalMarks: 44,
        maxExternal: 50,
        totalMarks: 87,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Dr. H. P. Roy',
      },
    ],
  },
  {
    semesterNumber: 1,
    academicYear: '2023-2024',
    examMonthYear: 'December 2023',
    issueDate: 'January 20, 2024',
    marksheetNo: 'SAP-MS-2024-01-38290',
    sgpa: 8.80,
    cgpa: 8.80,
    totalCredits: 20,
    resultStatus: 'Passed with Distinction',
    subjects: [
      {
        code: 'MA-101',
        title: 'Engineering Mathematics I',
        credits: 4,
        internalMarks: 28,
        maxInternal: 30,
        externalMarks: 64,
        maxExternal: 70,
        totalMarks: 92,
        maxTotal: 100,
        grade: 'A+',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Dr. K. S. Raman',
      },
      {
        code: 'CY-101',
        title: 'Engineering Chemistry & Materials',
        credits: 4,
        internalMarks: 25,
        maxInternal: 30,
        externalMarks: 59,
        maxExternal: 70,
        totalMarks: 84,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Dr. Shalini Gupta',
      },
      {
        code: 'ME-101',
        title: 'Engineering Mechanics & Graphics',
        credits: 4,
        internalMarks: 26,
        maxInternal: 30,
        externalMarks: 57,
        maxExternal: 70,
        totalMarks: 83,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Prof. Anand Joshi',
      },
      {
        code: 'EN-101',
        title: 'Technical Communication in English',
        credits: 3,
        internalMarks: 27,
        maxInternal: 30,
        externalMarks: 63,
        maxExternal: 70,
        totalMarks: 90,
        maxTotal: 100,
        grade: 'A+',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Dr. Sunita Kapoor',
      },
      {
        code: 'CY-102P',
        title: 'Chemistry Laboratory',
        credits: 2,
        internalMarks: 47,
        maxInternal: 50,
        externalMarks: 48,
        maxExternal: 50,
        totalMarks: 95,
        maxTotal: 100,
        grade: 'O (Outstanding)',
        gradePoints: 10,
        status: 'Pass',
        facultyName: 'Dr. Shalini Gupta',
      },
      {
        code: 'ME-102P',
        title: 'Manufacturing Practices & Carpentry',
        credits: 3,
        internalMarks: 44,
        maxInternal: 50,
        externalMarks: 45,
        maxExternal: 50,
        totalMarks: 89,
        maxTotal: 100,
        grade: 'A',
        gradePoints: 9,
        status: 'Pass',
        facultyName: 'Prof. Anand Joshi',
      },
    ],
  },
];

export const STUDENT_ATTENDANCE: SubjectAttendance[] = [
  {
    subjectCode: 'CS-501',
    subjectTitle: 'Cloud Architecture & Microservices',
    facultyName: 'Dr. Meera Nambiar',
    lecturesAttended: 38,
    totalLectures: 42,
    percentage: 90.5,
    lastAttended: 'Today, 10:00 AM',
    status: 'Good',
  },
  {
    subjectCode: 'CS-502',
    subjectTitle: 'Database Internals & Distributed Systems',
    facultyName: 'Prof. Ramesh Kulkarni',
    lecturesAttended: 34,
    totalLectures: 40,
    percentage: 85.0,
    lastAttended: 'Yesterday, 11:30 AM',
    status: 'Good',
  },
  {
    subjectCode: 'CS-503',
    subjectTitle: 'Software Engineering & SAP ABAP/UI5',
    facultyName: 'Dr. Anita Desai',
    lecturesAttended: 41,
    totalLectures: 44,
    percentage: 93.2,
    lastAttended: 'Today, 02:00 PM',
    status: 'Good',
  },
  {
    subjectCode: 'CS-504',
    subjectTitle: 'Artificial Intelligence & Machine Learning',
    facultyName: 'Prof. Vikram Sen',
    lecturesAttended: 27,
    totalLectures: 38,
    percentage: 71.1, // Warning: < 75%
    lastAttended: '2 days ago',
    status: 'Warning',
  },
  {
    subjectCode: 'CS-505P',
    subjectTitle: 'Cloud & AI Lab Practical',
    facultyName: 'Dr. Meera Nambiar',
    lecturesAttended: 19,
    totalLectures: 20,
    percentage: 95.0,
    lastAttended: '3 days ago',
    status: 'Good',
  },
  {
    subjectCode: 'CS-506P',
    subjectTitle: 'Industrial Mini Project',
    facultyName: 'Dr. Anita Desai',
    lecturesAttended: 15,
    totalLectures: 16,
    percentage: 93.8,
    lastAttended: 'Yesterday, 03:30 PM',
    status: 'Good',
  },
];

export const DAILY_ATTENDANCE_LOG: DailyAttendanceRecord[] = [
  {
    id: 'att_001',
    date: '2026-09-09',
    subjectCode: 'CS-501',
    subjectTitle: 'Cloud Architecture & Microservices',
    timeSlot: '09:00 AM - 10:00 AM',
    status: 'Present',
    markedBy: 'Dr. Meera Nambiar',
  },
  {
    id: 'att_002',
    date: '2026-09-09',
    subjectCode: 'CS-503',
    subjectTitle: 'Software Engineering & SAP ABAP/UI5',
    timeSlot: '02:00 PM - 03:00 PM',
    status: 'Present',
    markedBy: 'Dr. Anita Desai',
  },
  {
    id: 'att_003',
    date: '2026-09-08',
    subjectCode: 'CS-502',
    subjectTitle: 'Database Internals & Distributed Systems',
    timeSlot: '11:00 AM - 12:00 PM',
    status: 'Present',
    markedBy: 'Prof. Ramesh Kulkarni',
  },
  {
    id: 'att_004',
    date: '2026-09-07',
    subjectCode: 'CS-504',
    subjectTitle: 'Artificial Intelligence & Machine Learning',
    timeSlot: '10:00 AM - 11:00 AM',
    status: 'Absent',
    markedBy: 'Prof. Vikram Sen',
  },
  {
    id: 'att_005',
    date: '2026-09-06',
    subjectCode: 'CS-505P',
    subjectTitle: 'Cloud & AI Lab Practical',
    timeSlot: '02:00 PM - 04:00 PM',
    status: 'Present',
    markedBy: 'Dr. Meera Nambiar',
  },
  {
    id: 'att_006',
    date: '2026-09-05',
    subjectCode: 'CS-504',
    subjectTitle: 'Artificial Intelligence & Machine Learning',
    timeSlot: '09:00 AM - 10:00 AM',
    status: 'Late',
    markedBy: 'Prof. Vikram Sen',
  },
  {
    id: 'att_007',
    date: '2026-09-04',
    subjectCode: 'CS-501',
    subjectTitle: 'Cloud Architecture & Microservices',
    timeSlot: '09:00 AM - 10:00 AM',
    status: 'Present',
    markedBy: 'Dr. Meera Nambiar',
  },
];

export const FEE_INVOICES: FeeInvoice[] = [
  {
    id: 'inv_sem5_2025',
    invoiceNumber: 'SAP-INV-2025-05-4821',
    semester: 5,
    academicYear: '2025-2026 (Odd Sem)',
    totalAmount: 48500,
    paidAmount: 48500,
    dueAmount: 0,
    dueDate: '2025-08-15',
    status: 'Paid',
    paymentDate: '2025-08-10',
    transactionRef: 'TXN_SAP_948210398',
    paymentMethod: 'Online NetBanking (HDFC Bank)',
    breakdown: [
      { label: 'Tuition Fee (Semester 5)', amount: 35000 },
      { label: 'Cloud Computing & AI Lab Facility', amount: 6500 },
      { label: 'Digital Library & IEEE Resource Access', amount: 2500 },
      { label: 'SAP University Alliances License', amount: 2000 },
      { label: 'Semester Examination & Grade Portal Fee', amount: 2500 },
    ],
  },
  {
    id: 'inv_sem6_2026',
    invoiceNumber: 'SAP-INV-2026-06-5912',
    semester: 6,
    academicYear: '2025-2026 (Even Sem)',
    totalAmount: 51000,
    paidAmount: 25000,
    dueAmount: 26000,
    dueDate: '2026-09-30',
    status: 'Partial',
    paymentDate: '2026-08-28',
    transactionRef: 'TXN_SAP_827110514',
    paymentMethod: 'UPI (Google Pay)',
    breakdown: [
      { label: 'Tuition Fee (Semester 6)', amount: 36000 },
      { label: 'Advanced Cloud & Capstone Project Facility', amount: 7500 },
      { label: 'Library & Digital Journals', amount: 2500 },
      { label: 'Placement Training & Assessment Fee', amount: 2500 },
      { label: 'End-Term Examination Fee', amount: 2500 },
    ],
  },
  {
    id: 'inv_sem4_2025',
    invoiceNumber: 'SAP-INV-2025-04-3320',
    semester: 4,
    academicYear: '2024-2025 (Even Sem)',
    totalAmount: 47000,
    paidAmount: 47000,
    dueAmount: 0,
    dueDate: '2025-01-20',
    status: 'Paid',
    paymentDate: '2025-01-15',
    transactionRef: 'TXN_SAP_719002341',
    paymentMethod: 'Credit Card (Visa)',
    breakdown: [
      { label: 'Tuition Fee (Semester 4)', amount: 34000 },
      { label: 'Computer Lab Maintenance', amount: 6000 },
      { label: 'Library Fee', amount: 2500 },
      { label: 'Sports & Student Activities', amount: 2000 },
      { label: 'Examination Fee', amount: 2500 },
    ],
  },
];

export const STUDENT_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc_01',
    title: 'Semester 5 Official Grade Marksheet',
    type: 'Marksheet',
    fileName: 'Semester_5_Transcript_Aarav_Sharma.pdf',
    fileSize: '1.4 MB',
    uploadDate: '2026-01-16',
    status: 'Ready to Download',
    semester: 5,
  },
  {
    id: 'doc_02',
    title: 'Semester 4 Official Grade Marksheet',
    type: 'Marksheet',
    fileName: 'Semester_4_Transcript_Aarav_Sharma.pdf',
    fileSize: '1.3 MB',
    uploadDate: '2025-07-12',
    status: 'Ready to Download',
    semester: 4,
  },
  {
    id: 'doc_03',
    title: 'Semester 3 Official Grade Marksheet',
    type: 'Marksheet',
    fileName: 'Semester_3_Transcript_Aarav_Sharma.pdf',
    fileSize: '1.2 MB',
    uploadDate: '2025-01-22',
    status: 'Ready to Download',
    semester: 3,
  },
  {
    id: 'doc_04',
    title: 'Official Bonafide & Enrollment Certificate',
    type: 'Bonafide',
    fileName: 'Bonafide_Certificate_2025_26.pdf',
    fileSize: '820 KB',
    uploadDate: '2025-09-02',
    status: 'Verified',
  },
  {
    id: 'doc_05',
    title: 'Digital Student ID Card (RFID Verified)',
    type: 'ID_Card',
    fileName: 'Smart_Campus_Student_ID.pdf',
    fileSize: '650 KB',
    uploadDate: '2023-08-01',
    status: 'Verified',
  },
  {
    id: 'doc_06',
    title: 'Semester 6 Partial Fee Payment Receipt',
    type: 'Fee_Receipt',
    fileName: 'Fee_Receipt_SAP_INV_2026_06.pdf',
    fileSize: '410 KB',
    uploadDate: '2026-08-28',
    status: 'Ready to Download',
  },
];

export const NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif_01',
    title: 'Semester 5 Official Marksheet Published',
    description: 'The Examination Controller has released the verified Semester 5 grade card. SGPA: 8.85.',
    timestamp: '2 hours ago',
    read: false,
    type: 'academic',
    priority: 'High',
    actionPath: 'results',
    targetRole: 'student',
  },
  {
    id: 'notif_02',
    title: 'Fee Installment Reminder (Sem 6)',
    description: 'Remaining fee balance of ₹26,000 for Semester 6 is due on September 30, 2026.',
    timestamp: 'Yesterday',
    read: false,
    type: 'fee',
    priority: 'High',
    actionPath: 'fees',
    targetRole: 'student',
  },
  {
    id: 'notif_03',
    title: 'Attendance Shortage Advisory: CS-504',
    description: 'Your attendance in Artificial Intelligence (CS-504) is 71.1%, which is below the mandatory 75% threshold.',
    timestamp: '2 days ago',
    read: false,
    type: 'attendance',
    priority: 'High',
    actionPath: 'attendance',
    targetRole: 'student',
  },
  {
    id: 'notif_04',
    title: 'Faculty Grade Submission Deadline',
    description: 'Faculty members must submit internal midterm marks for Semester 5 by Friday 5:00 PM.',
    timestamp: '3 days ago',
    read: true,
    type: 'academic',
    priority: 'Medium',
    targetRole: 'teacher',
  },
  {
    id: 'notif_05',
    title: 'SAP S/4HANA Campus System Maintenance',
    description: 'University ERP maintenance scheduled for Sunday midnight. No downtime expected for student portal.',
    timestamp: '4 days ago',
    read: true,
    type: 'announcement',
    priority: 'Low',
    targetRole: 'all',
  },
];

export const FACULTY_COURSES: CourseAssignment[] = [
  {
    id: 'crs_01',
    code: 'CS-501',
    title: 'Cloud Architecture & Microservices',
    department: 'Computer Science',
    semester: 5,
    credits: 4,
    enrolledStudentsCount: 64,
    schedule: 'Mon, Wed, Fri 09:00 - 10:00 AM',
    room: 'Hall B-204 (Tech Block)',
    classAverageMarks: 82.4,
    attendanceRate: 88.6,
  },
  {
    id: 'crs_02',
    code: 'CS-505P',
    title: 'Cloud & AI Lab Practical',
    department: 'Computer Science',
    semester: 5,
    credits: 3,
    enrolledStudentsCount: 32,
    schedule: 'Tuesday 02:00 - 05:00 PM',
    room: 'Advanced Cloud Computing Lab 3',
    classAverageMarks: 89.1,
    attendanceRate: 94.2,
  },
  {
    id: 'crs_03',
    code: 'CS-301',
    title: 'Data Structures & Algorithms (Batch B)',
    department: 'Computer Science',
    semester: 3,
    credits: 4,
    enrolledStudentsCount: 58,
    schedule: 'Tue, Thu 11:30 - 01:00 PM',
    room: 'Hall A-102 (Aryabhatta Wing)',
    classAverageMarks: 76.8,
    attendanceRate: 81.5,
  },
];

export const ALL_STUDENTS_RECORD: StudentRecord[] = [
  {
    id: 'std_01',
    studentId: 'SAP-CS-2023-049',
    fullName: 'Aarav Sharma',
    email: 'aarav.sharma@sap-campus.edu.in',
    phone: '+91 98765 43210',
    department: 'Computer Science & Engineering',
    program: 'B.Tech - Computer Science',
    currentSemester: 5,
    cgpa: 8.72,
    attendanceRate: 88.4,
    feeStatus: 'Partial',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_02',
    studentId: 'SAP-CS-2023-012',
    fullName: 'Ananya Deshmukh',
    email: 'ananya.deshmukh@sap-campus.edu.in',
    phone: '+91 98220 11223',
    department: 'Computer Science & Engineering',
    program: 'B.Tech - Computer Science',
    currentSemester: 5,
    cgpa: 9.35,
    attendanceRate: 96.0,
    feeStatus: 'Paid',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_03',
    studentId: 'SAP-CS-2023-033',
    fullName: 'Rohan Verma',
    email: 'rohan.verma@sap-campus.edu.in',
    phone: '+91 97410 44556',
    department: 'Computer Science & Engineering',
    program: 'B.Tech - Computer Science',
    currentSemester: 5,
    cgpa: 7.15,
    attendanceRate: 68.2, // Below mandatory 75%
    feeStatus: 'Pending',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_04',
    studentId: 'SAP-CS-2023-078',
    fullName: 'Priya Sundaram',
    email: 'priya.sundaram@sap-campus.edu.in',
    phone: '+91 98830 77889',
    department: 'Computer Science & Engineering',
    program: 'B.Tech - Computer Science',
    currentSemester: 5,
    cgpa: 8.90,
    attendanceRate: 91.5,
    feeStatus: 'Paid',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_05',
    studentId: 'SAP-ECE-2023-021',
    fullName: 'Vikramaditya Rao',
    email: 'vikram.rao@sap-campus.edu.in',
    phone: '+91 96111 88220',
    department: 'Electronics & Communication',
    program: 'B.Tech - ECE',
    currentSemester: 5,
    cgpa: 8.24,
    attendanceRate: 84.0,
    feeStatus: 'Paid',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_06',
    studentId: 'SAP-ME-2023-005',
    fullName: 'Siddharth Menon',
    email: 'siddharth.menon@sap-campus.edu.in',
    phone: '+91 99450 33112',
    department: 'Mechanical Engineering',
    program: 'B.Tech - ME',
    currentSemester: 5,
    cgpa: 7.82,
    attendanceRate: 74.0, // Borderline
    feeStatus: 'Partial',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_07',
    studentId: 'SAP-CS-2023-092',
    fullName: 'Diya Sengupta',
    email: 'diya.sengupta@sap-campus.edu.in',
    phone: '+91 98301 22445',
    department: 'Computer Science & Engineering',
    program: 'B.Tech - Computer Science',
    currentSemester: 5,
    cgpa: 9.12,
    attendanceRate: 94.5,
    feeStatus: 'Paid',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_08',
    studentId: 'SAP-CS-2023-064',
    fullName: 'Aryan Patel',
    email: 'aryan.patel@sap-campus.edu.in',
    phone: '+91 97245 66778',
    department: 'Computer Science & Engineering',
    program: 'B.Tech - Computer Science',
    currentSemester: 5,
    cgpa: 8.45,
    attendanceRate: 86.2,
    feeStatus: 'Paid',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_09',
    studentId: 'SAP-ECE-2023-044',
    fullName: 'Tanvi Joshi',
    email: 'tanvi.joshi@sap-campus.edu.in',
    phone: '+91 98231 99001',
    department: 'Electronics & Communication',
    program: 'B.Tech - ECE',
    currentSemester: 5,
    cgpa: 8.68,
    attendanceRate: 89.0,
    feeStatus: 'Paid',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_10',
    studentId: 'SAP-CS-2023-118',
    fullName: 'Ishaan Mukherjee',
    email: 'ishaan.m@sap-campus.edu.in',
    phone: '+91 98450 77114',
    department: 'Computer Science & Engineering',
    program: 'B.Tech - Computer Science',
    currentSemester: 5,
    cgpa: 7.60,
    attendanceRate: 72.5, // Below 75%
    feeStatus: 'Pending',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_11',
    studentId: 'SAP-CE-2023-014',
    fullName: 'Neha Kulkarni',
    email: 'neha.kulkarni@sap-campus.edu.in',
    phone: '+91 99224 55667',
    department: 'Civil Engineering',
    program: 'B.Tech - Civil Eng',
    currentSemester: 5,
    cgpa: 8.32,
    attendanceRate: 92.0,
    feeStatus: 'Paid',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
  },
  {
    id: 'std_12',
    studentId: 'SAP-ME-2023-038',
    fullName: 'Aditya Nair',
    email: 'aditya.nair@sap-campus.edu.in',
    phone: '+91 94471 88990',
    department: 'Mechanical Engineering',
    program: 'B.Tech - ME',
    currentSemester: 5,
    cgpa: 8.05,
    attendanceRate: 85.5,
    feeStatus: 'Paid',
    status: 'Active',
    avatarUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80',
  },
];

export const STUDENT_TIMETABLE: TimetableSlot[] = [
  // Monday
  {
    id: 'tt_mon_1',
    day: 'Monday',
    periodNumber: 1,
    timeSlot: '09:00 AM - 10:00 AM',
    subjectCode: 'CS-501',
    subjectTitle: 'Cloud Architecture & Microservices',
    room: 'Hall B-204 (Tech Block)',
    facultyName: 'Dr. Meera Nambiar',
    type: 'Lecture',
    status: 'Completed',
  },
  {
    id: 'tt_mon_2',
    day: 'Monday',
    periodNumber: 2,
    timeSlot: '10:15 AM - 11:15 AM',
    subjectCode: 'CS-502',
    subjectTitle: 'Database Internals & Distributed Systems',
    room: 'Hall B-204 (Tech Block)',
    facultyName: 'Prof. Ramesh Kulkarni',
    type: 'Lecture',
    status: 'Completed',
  },
  {
    id: 'tt_mon_3',
    day: 'Monday',
    periodNumber: 3,
    timeSlot: '11:30 AM - 12:30 PM',
    subjectCode: 'CS-504',
    subjectTitle: 'Artificial Intelligence & Machine Learning',
    room: 'Hall A-108 (Aryabhatta Wing)',
    facultyName: 'Prof. Vikram Sen',
    type: 'Lecture',
    status: 'Completed',
  },
  {
    id: 'tt_mon_4',
    day: 'Monday',
    periodNumber: 4,
    timeSlot: '02:00 PM - 04:00 PM',
    subjectCode: 'CS-505P',
    subjectTitle: 'Cloud & AI Lab Practical (Batch A)',
    room: 'Advanced Cloud Computing Lab 3',
    facultyName: 'Dr. Meera Nambiar',
    type: 'Lab',
    status: 'Completed',
  },

  // Tuesday
  {
    id: 'tt_tue_1',
    day: 'Tuesday',
    periodNumber: 1,
    timeSlot: '09:00 AM - 10:00 AM',
    subjectCode: 'CS-503',
    subjectTitle: 'Software Engineering & SAP ABAP/UI5',
    room: 'Computing Hall 4',
    facultyName: 'Dr. Anita Desai',
    type: 'Lecture',
    status: 'Completed',
  },
  {
    id: 'tt_tue_2',
    day: 'Tuesday',
    periodNumber: 2,
    timeSlot: '10:15 AM - 11:15 AM',
    subjectCode: 'CS-501',
    subjectTitle: 'Cloud Architecture & Microservices',
    room: 'Hall B-204 (Tech Block)',
    facultyName: 'Dr. Meera Nambiar',
    type: 'Lecture',
    status: 'Completed',
  },
  {
    id: 'tt_tue_3',
    day: 'Tuesday',
    periodNumber: 3,
    timeSlot: '11:30 AM - 12:30 PM',
    subjectCode: 'CS-502',
    subjectTitle: 'Database Internals & Distributed Systems',
    room: 'Hall B-204 (Tech Block)',
    facultyName: 'Prof. Ramesh Kulkarni',
    type: 'Tutorial',
    status: 'Completed',
  },
  {
    id: 'tt_tue_4',
    day: 'Tuesday',
    periodNumber: 4,
    timeSlot: '02:00 PM - 05:00 PM',
    subjectCode: 'CS-506P',
    subjectTitle: 'Industrial Mini Project & SAP Design Thinking',
    room: 'Innovation Sandbox Hub',
    facultyName: 'Dr. Anita Desai',
    type: 'Lab',
    status: 'Completed',
  },

  // Wednesday (Today)
  {
    id: 'tt_wed_1',
    day: 'Wednesday',
    periodNumber: 1,
    timeSlot: '09:00 AM - 10:00 AM',
    subjectCode: 'CS-501',
    subjectTitle: 'Cloud Architecture & Microservices',
    room: 'Hall B-204 (Tech Block)',
    facultyName: 'Dr. Meera Nambiar',
    type: 'Lecture',
    status: 'Completed',
  },
  {
    id: 'tt_wed_2',
    day: 'Wednesday',
    periodNumber: 2,
    timeSlot: '10:15 AM - 11:15 AM',
    subjectCode: 'CS-504',
    subjectTitle: 'Artificial Intelligence & Machine Learning',
    room: 'Hall A-108 (Aryabhatta Wing)',
    facultyName: 'Prof. Vikram Sen',
    type: 'Lecture',
    status: 'Completed',
  },
  {
    id: 'tt_wed_3',
    day: 'Wednesday',
    periodNumber: 3,
    timeSlot: '02:00 PM - 03:00 PM',
    subjectCode: 'CS-503',
    subjectTitle: 'Software Engineering & SAP ABAP/UI5',
    room: 'Computing Hall 4',
    facultyName: 'Dr. Anita Desai',
    type: 'Lecture',
    status: 'Live',
    notes: 'SAP UI5 Component Lifecycle & OData Binding in Progress',
  },
  {
    id: 'tt_wed_4',
    day: 'Wednesday',
    periodNumber: 4,
    timeSlot: '03:15 PM - 05:15 PM',
    subjectCode: 'CS-505P',
    subjectTitle: 'Cloud & AI Lab Practical (Batch B)',
    room: 'Advanced Cloud Computing Lab 3',
    facultyName: 'Dr. Meera Nambiar',
    type: 'Lab',
    status: 'Upcoming',
  },

  // Thursday
  {
    id: 'tt_thu_1',
    day: 'Thursday',
    periodNumber: 1,
    timeSlot: '09:00 AM - 10:00 AM',
    subjectCode: 'CS-502',
    subjectTitle: 'Database Internals & Distributed Systems',
    room: 'Hall B-204 (Tech Block)',
    facultyName: 'Prof. Ramesh Kulkarni',
    type: 'Lecture',
    status: 'Upcoming',
  },
  {
    id: 'tt_thu_2',
    day: 'Thursday',
    periodNumber: 2,
    timeSlot: '10:15 AM - 11:15 AM',
    subjectCode: 'CS-503',
    subjectTitle: 'Software Engineering & SAP ABAP/UI5',
    room: 'Computing Hall 4',
    facultyName: 'Dr. Anita Desai',
    type: 'Lecture',
    status: 'Upcoming',
  },
  {
    id: 'tt_thu_3',
    day: 'Thursday',
    periodNumber: 3,
    timeSlot: '11:30 AM - 12:30 PM',
    subjectCode: 'CS-504',
    subjectTitle: 'Artificial Intelligence & Machine Learning',
    room: 'Hall A-108 (Aryabhatta Wing)',
    facultyName: 'Prof. Vikram Sen',
    type: 'Tutorial',
    status: 'Upcoming',
  },
  {
    id: 'tt_thu_4',
    day: 'Thursday',
    periodNumber: 4,
    timeSlot: '02:00 PM - 04:00 PM',
    subjectCode: 'CS-501',
    subjectTitle: 'Cloud DevOps Workshop & Kubernetes',
    room: 'Seminar Hall 2 (Main Campus)',
    facultyName: 'Dr. Meera Nambiar',
    type: 'Seminar',
    status: 'Upcoming',
  },

  // Friday
  {
    id: 'tt_fri_1',
    day: 'Friday',
    periodNumber: 1,
    timeSlot: '09:00 AM - 10:00 AM',
    subjectCode: 'CS-504',
    subjectTitle: 'Artificial Intelligence & Machine Learning',
    room: 'Hall A-108 (Aryabhatta Wing)',
    facultyName: 'Prof. Vikram Sen',
    type: 'Lecture',
    status: 'Upcoming',
  },
  {
    id: 'tt_fri_2',
    day: 'Friday',
    periodNumber: 2,
    timeSlot: '10:15 AM - 11:15 AM',
    subjectCode: 'CS-501',
    subjectTitle: 'Cloud Architecture & Microservices',
    room: 'Hall B-204 (Tech Block)',
    facultyName: 'Dr. Meera Nambiar',
    type: 'Lecture',
    status: 'Upcoming',
  },
  {
    id: 'tt_fri_3',
    day: 'Friday',
    periodNumber: 3,
    timeSlot: '11:30 AM - 01:00 PM',
    subjectCode: 'CS-506P',
    subjectTitle: 'Project Review & Colloquium',
    room: 'Auditorium Block C',
    facultyName: 'Dr. Anita Desai',
    type: 'Seminar',
    status: 'Upcoming',
  },
  {
    id: 'tt_fri_4',
    day: 'Friday',
    periodNumber: 4,
    timeSlot: '02:30 PM - 04:30 PM',
    subjectCode: 'SAP-IND',
    subjectTitle: 'SAP University Alliances Industry Session',
    room: 'Executive Briefing Room',
    facultyName: 'Industry Expert (SAP Labs)',
    type: 'Seminar',
    status: 'Upcoming',
  },
];

